version = 1

test_patterns = [
  "public/**",
  "src/**"
]

exclude_patterns = ["src/components/assets/img/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "standardjs"
enabled = true
